-- V8__improve_onboarding_structure.sql
-- Enhanced onboarding tracking and profile structure

-- Add missing onboarding fields to users table if not already present
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS headline VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_website VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(512);

-- Create onboarding_progress table to track multi-step onboarding
CREATE TABLE IF NOT EXISTS onboarding_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    current_step INTEGER NOT NULL DEFAULT 1,
    max_step_reached INTEGER NOT NULL DEFAULT 1,
    step_1_completed BOOLEAN DEFAULT FALSE,
    step_2_completed BOOLEAN DEFAULT FALSE,
    step_3_completed BOOLEAN DEFAULT FALSE,
    step_4_completed BOOLEAN DEFAULT FALSE,
    step_5_completed BOOLEAN DEFAULT FALSE,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_onboarding_progress_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

-- Create recruiter_profile table for recruiter-specific data
CREATE TABLE IF NOT EXISTS recruiter_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    company_name VARCHAR(255),
    company_website VARCHAR(255),
    company_logo_url VARCHAR(512),
    industry VARCHAR(100),
    company_size VARCHAR(50),
    verified BOOLEAN DEFAULT FALSE,
    verified_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recruiter_profile_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

-- Create job_seeker_profile table for job seeker-specific data
CREATE TABLE IF NOT EXISTS job_seeker_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    professional_headline VARCHAR(255),
    skills TEXT,
    experience_years INTEGER,
    current_company VARCHAR(255),
    current_designation VARCHAR(255),
    education TEXT,
    profile_completion_percentage INTEGER DEFAULT 0,
    open_to_opportunities BOOLEAN DEFAULT TRUE,
    expected_salary_min DECIMAL(12,2),
    expected_salary_max DECIMAL(12,2),
    salary_currency VARCHAR(10) DEFAULT 'INR',
    work_preference VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_job_seeker_profile_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

-- Add indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_onboarding_progress_user_id
    ON onboarding_progress (user_id);

CREATE INDEX IF NOT EXISTS idx_onboarding_progress_completed_at
    ON onboarding_progress (completed_at DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS idx_recruiter_profile_user_id
    ON recruiter_profile (user_id);

CREATE INDEX IF NOT EXISTS idx_job_seeker_profile_user_id
    ON job_seeker_profile (user_id);

-- Update resumes table to support multiple resumes and add metadata
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS is_primary BOOLEAN DEFAULT FALSE;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS parsed_skills TEXT;

-- Create index for faster primary resume lookups
CREATE INDEX IF NOT EXISTS idx_resumes_user_primary
    ON resumes (user_id, is_primary) WHERE is_primary = TRUE;
