-- Vecta initial schema for Supabase (PostgreSQL)
-- Generated from backend JPA entities.

begin;

create table if not exists users (
    id bigint generated by default as identity primary key,
    username varchar(255) not null unique,
    password varchar(255) not null,
    email varchar(255) not null unique,
    role varchar(50) not null,
    failed_login_attempts integer not null default 0,
    lock_until timestamp,
    email_verified boolean not null default false,
    email_verification_token varchar(128),
    email_verification_expiry timestamp,
    password_reset_token varchar(128),
    password_reset_expiry timestamp,
    token_version bigint not null default 0,
    mfa_enabled boolean not null default false,
    mfa_secret varchar(64),
    last_login_ip varchar(255),
    last_login_user_agent varchar(512),
    last_login_at timestamp,
    constraint chk_users_role
        check (role in ('ADMIN', 'RECRUITER', 'JOB_SEEKER'))
);

create index if not exists idx_users_email_verification_token
    on users (email_verification_token);

create index if not exists idx_users_password_reset_token
    on users (password_reset_token);

create table if not exists jobs (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description text,
    location varchar(255),
    recruiter_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_jobs_recruiter
        foreign key (recruiter_id) references users (id)
);

create index if not exists idx_jobs_recruiter_id
    on jobs (recruiter_id);

create index if not exists idx_jobs_created_at
    on jobs (created_at desc);

create index if not exists idx_jobs_title_lower
    on jobs (lower(title));

create index if not exists idx_jobs_location_lower
    on jobs (lower(location));

create table if not exists resumes (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    file_name varchar(255),
    file_type varchar(100),
    data bytea,
    uploaded_at timestamp not null default current_timestamp,
    constraint fk_resumes_owner
        foreign key (user_id) references users (id)
);

create table if not exists applications (
    id bigint generated by default as identity primary key,
    applicant_id bigint not null,
    job_id bigint not null,
    resume_id bigint,
    status varchar(50) not null default 'APPLIED',
    applied_at timestamp not null default current_timestamp,
    constraint fk_applications_applicant
        foreign key (applicant_id) references users (id),
    constraint fk_applications_job
        foreign key (job_id) references jobs (id),
    constraint fk_applications_resume
        foreign key (resume_id) references resumes (id),
    constraint chk_applications_status
        check (status in ('APPLIED', 'SHORTLISTED', 'REJECTED', 'HIRED')),
    constraint uq_applications_applicant_job
        unique (applicant_id, job_id)
);

create index if not exists idx_applications_job_id
    on applications (job_id);

create index if not exists idx_applications_applicant_id
    on applications (applicant_id);

create index if not exists idx_applications_applied_at
    on applications (applied_at desc);

commit;
