-- Migration: Sync Onboarding, Slugs and Application Links
-- Date: 2026-04-27

-- 1. Job Table Enhancements
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS application_link TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS slug VARCHAR(255) UNIQUE;

-- 2. User Table Enhancements (Onboarding)
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS headline VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS company_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS skills TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture_url VARCHAR(512);
